language: elixir
elixir:
  - "1.9"
otp_release:
  - "22.0"

services:
  - postgresql

before_install:
  - nvm install 10
  - echo $TRAVIS_COMMIT_RANGE
  - ./scripts/echo.sh

install:
  - yarn install --frozen-lockfile
  - sh -c 'cd api && mix local.rebar --force; mix local.hex --force; mix deps.get'
  - sh -c 'cd client && yarn install --frozen-lockfile'

before_script:
  - sh -c 'cd api && mix ecto.create'

script:
  - yarn format:check
  - yarn test
