language: elixir
elixir:
  - "1.9"
otp_release:
  - "22.0"

services:
  - postgresql

before_install:
  - cd api

before_script:
  - mix ecto.create

script:
  - mix format --check-formatted
  - mix test

after_success:
  - cd ..

deploy:
  provider: script
  script: bash api/scripts/deploy.sh
  on:
    branch: master
