language: elixir
elixir:
  - "1.7"
otp_release:
  - "21.0"

services:
  - postgresql

before_script:
  - mix ecto.create

script:
  - mix format --check-formatted
  - mix test

deploy:
  provider: script
  script: bash scripts/deploy-gigalixir.sh
  on:
    branch: master
