name: Elixir API CI

on:
  push:
    paths:
      - '.github/workflows/api.yml'
      - 'api/**'

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: elixir:1.9-slim
    
    services:
      postgresql:
        image: postgres

    steps:
    - uses: actions/checkout@v1
    - name: Change working directory
      run: cd api/
    - name: Install dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Setup database
      run: mix ecto.create
    - name: Check formatting
      run: mix format --check-formatted
    - name: Run tests
      run: mix test
